version: '3.8'

services:
  frontend:
    image: phihocnguyen123/restaurant-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - BACKEND_URL=http://backend:8081
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: phihocnguyen123/restaurant-backend:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/restaurant
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - CLOUDINARY_CLOUD_NAME=dpbk5trba
      - CLOUDINARY_API_KEY=939765944348812
      - CLOUDINARY_API_SECRET=BlifYk_whZmFdRbsCS1lm9JfT4w
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=hankhongg@gmail.com
      - SPRING_MAIL_PASSWORD=ghzs whgw orxa hwqf
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=restaurant
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 